name: basic-ci

on:
  - push
  - pull_request

jobs:
  ci:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: ts
        run: npm run ts:check
      - name: compile
        run: npm run compile
      - name: test node fail
        run: node ./dist/index.js
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: prettier
        run: npm run format:check
